using System;
using System.Collections.Generic;
using System.Data.Common;
using Smart.Model;
using Smart.Database;
using GerenciamentoContatos.Model;

namespace GerenciamentoContatos.View
{
	public class CidadeContatoEstadoBLL : Smart.Model.BusinessObject
	{
		#region Automaticaly generated by Smart.AutoModeling 2.0
		public CidadeContatoEstadoBLL() { }

		public CidadeContatoEstadoBLL(DbConn pDbHnd) : base (pDbHnd) { }


		public List<CidadeContatoEstadoView> AutoGeneratedQuery()
		{
			CidadeContatoEstadoDAL dal = new CidadeContatoEstadoDAL(this.DbHnd);
			dal.Filters = this.Filters;
			return dal.AutoGeneratedQuery();
		}
		#endregion
	}
	public class CidadeContatoEstadoDAL : Smart.Model.DataAccessObject
	{
		#region Automaticaly generated by Smart.AutoModeling 2.0
		public CidadeContatoEstadoDAL(DbConn pDbHnd) : base (pDbHnd) { }

		public List<CidadeContatoEstadoView> AutoGeneratedQuery()
		{
			List<CidadeContatoEstadoView> lstReturn = new List<CidadeContatoEstadoView>();

			String sqlSelect = "CIDADE.cd_cidade, CIDADE.cd_estado, CIDADE.ds_cidade, CONTATO.cd_contato, CONTATO.cd_cidade, CONTATO.cd_estado, CONTATO.dt_nascimento, CONTATO.ds_cpf, CONTATO.ds_nome, CONTATO.ds_email, CONTATO.ds_endereco, ESTADO.cd_estado, ESTADO.ds_estado, ESTADO.ds_uf";
			String sqlFrom = "CIDADE INNER JOIN CONTATO ON CIDADE.campo = CONTATO.campo INNER JOIN ESTADO ON CIDADE.campo = ESTADO.campo";
			String sqlWhere = BuildFilters();
			String sqlOrderBy = BuildOrderBy();
			using (DbDataReader dr = DbHnd.ExecuteReader("SELECT " + sqlSelect + " FROM " + sqlFrom + sqlWhere + sqlOrderBy))
			{
				while (dr.Read())
				{
					CidadeContatoEstadoView view = new CidadeContatoEstadoView();
					view.Cidade.CdCidade.Value = Convert.ToInt32(dr["cd_cidade"]);
					view.Cidade.CdEstado.Value = Convert.ToInt32(dr["cd_estado"]);
					view.Cidade.DsCidade.Value = dr["ds_cidade"].ToString();
					view.Contato.CdContato.Value = Convert.ToInt32(dr["cd_contato"]);
					view.Contato.CdCidade.Value = Convert.ToInt32(dr["cd_cidade"]);
					view.Contato.CdEstado.Value = Convert.ToInt32(dr["cd_estado"]);
					view.Contato.DtNascimento.Value = (DateTime)dr["dt_nascimento"];
					view.Contato.DsCpf.Value = dr["ds_cpf"].ToString();
					view.Contato.DsNome.Value = dr["ds_nome"].ToString();
					view.Contato.DsEmail.Value = dr["ds_email"].ToString();
					view.Contato.DsEndereco.Value = dr["ds_endereco"].ToString();
					view.Estado.CdEstado.Value = Convert.ToInt32(dr["cd_estado"]);
					view.Estado.DsEstado.Value = dr["ds_estado"].ToString();
					view.Estado.DsUf.Value = dr["ds_uf"].ToString();
					lstReturn.Add(view);
				}
			}
			return lstReturn;
		}
		#endregion
	}
	public class CidadeContatoEstadoView
	{
		#region Automaticaly generated by Smart.AutoModeling 2.0
		private CidadeInfo _Cidade = new CidadeInfo();
		public CidadeInfo Cidade
		{
			get { return _Cidade; }
			set { _Cidade = value; }
		}

		private ContatoInfo _Contato = new ContatoInfo();
		public ContatoInfo Contato
		{
			get { return _Contato; }
			set { _Contato = value; }
		}

		private EstadoInfo _Estado = new EstadoInfo();
		public EstadoInfo Estado
		{
			get { return _Estado; }
			set { _Estado = value; }
		}

		#endregion
	}
}
