using System;
using System.Data.Common;
using Smart.Database;
using Smart.Model;
using System.Collections.Generic;
using GerenciamentoContatos.Model;

namespace GerenciamentoContatos.DAL
{
	public class ContatoDAL : Smart.Model.DataAccessObject
	{
		#region Automaticaly generated by Smart.AutoModeling 2.0
		public ContatoDAL(DbConn pDbHnd) : base (pDbHnd) { }

		public ContatoInfo Get(Int32 pCdContato)
		{
			DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@cdContato", pCdContato));
			String sql = "SELECT cd_contato, cd_cidade, cd_estado, dt_nascimento, ds_cpf, ds_nome, ds_email, ds_endereco FROM CONTATO WHERE cd_contato = @cdContato";
			DbDataReader dr = DbHnd.ExecuteReader(sql);
			try
			{
				if (dr.Read())
				{
					ContatoInfo info = new ContatoInfo();
					if(dr["cd_contato"] != System.DBNull.Value)
						info.CdContato.Value = Convert.ToInt32(dr["cd_contato"]);
					else
					{
						if (info.CdContato.AllowsNull)
							info.CdContato.IsNullValue = true;
					}
					if(dr["cd_cidade"] != System.DBNull.Value)
						info.CdCidade.Value = Convert.ToInt32(dr["cd_cidade"]);
					else
					{
						if (info.CdCidade.AllowsNull)
							info.CdCidade.IsNullValue = true;
					}
					if(dr["cd_estado"] != System.DBNull.Value)
						info.CdEstado.Value = Convert.ToInt32(dr["cd_estado"]);
					else
					{
						if (info.CdEstado.AllowsNull)
							info.CdEstado.IsNullValue = true;
					}
					if(dr["dt_nascimento"] != System.DBNull.Value)
						info.DtNascimento.Value = (DateTime)dr["dt_nascimento"];
					else
					{
						if (info.DtNascimento.AllowsNull)
							info.DtNascimento.IsNullValue = true;
					}
					if(dr["ds_cpf"] != System.DBNull.Value)
						info.DsCpf.Value = dr["ds_cpf"].ToString();
					else
					{
						if (info.DsCpf.AllowsNull)
							info.DsCpf.IsNullValue = true;
					}
					if(dr["ds_nome"] != System.DBNull.Value)
						info.DsNome.Value = dr["ds_nome"].ToString();
					else
					{
						if (info.DsNome.AllowsNull)
							info.DsNome.IsNullValue = true;
					}
					if(dr["ds_email"] != System.DBNull.Value)
						info.DsEmail.Value = dr["ds_email"].ToString();
					else
					{
						if (info.DsEmail.AllowsNull)
							info.DsEmail.IsNullValue = true;
					}
					if(dr["ds_endereco"] != System.DBNull.Value)
						info.DsEndereco.Value = dr["ds_endereco"].ToString();
					else
					{
						if (info.DsEndereco.AllowsNull)
							info.DsEndereco.IsNullValue = true;
					}

					return info;
				}
				else
				{
					return null;
				}
			}
			finally
			{
				dr.Dispose();
			}
		}

		public Int32 Inserir(ContatoInfo pInfo)
		{
			String insertCols = String.Empty;
			String insertValues = String.Empty;
			if (pInfo.CdCidade.ValueIsSet)
			{
				if (!pInfo.CdCidade.IsNullValue)
				{
					DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@cdCidade", pInfo.CdCidade.Value));
				}
				else
				{
					DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@cdCidade", System.DBNull.Value));
				}
				insertCols += ", " + pInfo.CdCidade.Name;
				insertValues += ", @cdCidade";
			}
			if (pInfo.CdEstado.ValueIsSet)
			{
				if (!pInfo.CdEstado.IsNullValue)
				{
					DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@cdEstado", pInfo.CdEstado.Value));
				}
				else
				{
					DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@cdEstado", System.DBNull.Value));
				}
				insertCols += ", " + pInfo.CdEstado.Name;
				insertValues += ", @cdEstado";
			}
			if (pInfo.DtNascimento.ValueIsSet)
			{
				if (!pInfo.DtNascimento.IsNullValue)
				{
					DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dtNascimento", pInfo.DtNascimento.Value));
				}
				else
				{
					DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dtNascimento", System.DBNull.Value));
				}
				insertCols += ", " + pInfo.DtNascimento.Name;
				insertValues += ", @dtNascimento";
			}
			if (pInfo.DsCpf.ValueIsSet)
			{
				if (!pInfo.DsCpf.IsNullValue)
				{
					DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsCpf", pInfo.DsCpf.Value));
				}
				else
				{
					DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsCpf", System.DBNull.Value));
				}
				insertCols += ", " + pInfo.DsCpf.Name;
				insertValues += ", @dsCpf";
			}
			if (pInfo.DsNome.ValueIsSet)
			{
				if (!pInfo.DsNome.IsNullValue)
				{
					DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsNome", pInfo.DsNome.Value));
				}
				else
				{
					DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsNome", System.DBNull.Value));
				}
				insertCols += ", " + pInfo.DsNome.Name;
				insertValues += ", @dsNome";
			}
			if (pInfo.DsEmail.ValueIsSet)
			{
				if (!pInfo.DsEmail.IsNullValue)
				{
					DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsEmail", pInfo.DsEmail.Value));
				}
				else
				{
					DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsEmail", System.DBNull.Value));
				}
				insertCols += ", " + pInfo.DsEmail.Name;
				insertValues += ", @dsEmail";
			}
			if (pInfo.DsEndereco.ValueIsSet)
			{
				if (!pInfo.DsEndereco.IsNullValue)
				{
					DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsEndereco", pInfo.DsEndereco.Value));
				}
				else
				{
					DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsEndereco", System.DBNull.Value));
				}
				insertCols += ", " + pInfo.DsEndereco.Name;
				insertValues += ", @dsEndereco";
			}
			insertCols = insertCols.Substring(2, insertCols.Length - 2);
			insertValues = insertValues.Substring(2, insertValues.Length - 2);
			return DbHnd.InsertGetInt32Key("INSERT INTO CONTATO (" + insertCols + ") VALUES (" + insertValues + ")", "cd_contato");
		}

		public void Atualizar(Int32 pCdContato, ContatoInfo pInfo)
		{
			String upVars = String.Empty;
			if (pInfo.CdCidade.ValueIsSet)
			{
				if (!pInfo.CdCidade.IsNullValue)
				{
					DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@cdCidade", pInfo.CdCidade.Value));
				}
				else
				{
					DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@cdCidade", System.DBNull.Value));
				}
				upVars += ", " + pInfo.CdCidade.Name + " = @cdCidade";
			}
			if (pInfo.CdEstado.ValueIsSet)
			{
				if (!pInfo.CdEstado.IsNullValue)
				{
					DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@cdEstado", pInfo.CdEstado.Value));
				}
				else
				{
					DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@cdEstado", System.DBNull.Value));
				}
				upVars += ", " + pInfo.CdEstado.Name + " = @cdEstado";
			}
			if (pInfo.DtNascimento.ValueIsSet)
			{
				if (!pInfo.DtNascimento.IsNullValue)
				{
					DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dtNascimento", pInfo.DtNascimento.Value));
				}
				else
				{
					DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dtNascimento", System.DBNull.Value));
				}
				upVars += ", " + pInfo.DtNascimento.Name + " = @dtNascimento";
			}
			if (pInfo.DsCpf.ValueIsSet)
			{
				if (!pInfo.DsCpf.IsNullValue)
				{
					DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsCpf", pInfo.DsCpf.Value));
				}
				else
				{
					DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsCpf", System.DBNull.Value));
				}
				upVars += ", " + pInfo.DsCpf.Name + " = @dsCpf";
			}
			if (pInfo.DsNome.ValueIsSet)
			{
				if (!pInfo.DsNome.IsNullValue)
				{
					DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsNome", pInfo.DsNome.Value));
				}
				else
				{
					DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsNome", System.DBNull.Value));
				}
				upVars += ", " + pInfo.DsNome.Name + " = @dsNome";
			}
			if (pInfo.DsEmail.ValueIsSet)
			{
				if (!pInfo.DsEmail.IsNullValue)
				{
					DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsEmail", pInfo.DsEmail.Value));
				}
				else
				{
					DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsEmail", System.DBNull.Value));
				}
				upVars += ", " + pInfo.DsEmail.Name + " = @dsEmail";
			}
			if (pInfo.DsEndereco.ValueIsSet)
			{
				if (!pInfo.DsEndereco.IsNullValue)
				{
					DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsEndereco", pInfo.DsEndereco.Value));
				}
				else
				{
					DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsEndereco", System.DBNull.Value));
				}
				upVars += ", " + pInfo.DsEndereco.Name + " = @dsEndereco";
			}
			upVars = upVars.Substring(2, upVars.Length - 2);

			String sqlWhere = String.Empty;
			DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@cdContato", pCdContato));
			sqlWhere += "cd_contato = @cdContato";
			sqlWhere = " WHERE " + sqlWhere;

			DbHnd.ExecuteNonQuery("UPDATE CONTATO SET " + upVars + sqlWhere);
		}

		public void Deletar(Int32 pCdContato)
		{
			DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@cdContato", pCdContato));
			DbHnd.ExecuteNonQuery("DELETE FROM CONTATO WHERE cd_contato = @cdContato");
		}

		public List<ContatoInfo> Listar()
		{
			List<ContatoInfo> lstReturn = new List<ContatoInfo>();

			String sqlSelect = "cd_contato, cd_cidade, cd_estado, dt_nascimento, ds_cpf, ds_nome, ds_email, ds_endereco";
			String sqlFrom = "CONTATO";
			String sqlWhere = BuildFilters();
			String sqlOrderBy = BuildOrderBy();
			String sql = "SELECT " + sqlSelect + " FROM " + sqlFrom + sqlWhere + sqlOrderBy;
			using (DbDataReader dr = DbHnd.ExecuteReader(sql))
			{
				while (dr.Read())
				{
					ContatoInfo info = new ContatoInfo();
					if(dr["cd_contato"] != System.DBNull.Value)
						info.CdContato.Value = Convert.ToInt32(dr["cd_contato"]);
					else
					{
						if (info.CdContato.AllowsNull)
							info.CdContato.IsNullValue = true;
					}
					if(dr["cd_cidade"] != System.DBNull.Value)
						info.CdCidade.Value = Convert.ToInt32(dr["cd_cidade"]);
					else
					{
						if (info.CdCidade.AllowsNull)
							info.CdCidade.IsNullValue = true;
					}
					if(dr["cd_estado"] != System.DBNull.Value)
						info.CdEstado.Value = Convert.ToInt32(dr["cd_estado"]);
					else
					{
						if (info.CdEstado.AllowsNull)
							info.CdEstado.IsNullValue = true;
					}
					if(dr["dt_nascimento"] != System.DBNull.Value)
						info.DtNascimento.Value = (DateTime)dr["dt_nascimento"];
					else
					{
						if (info.DtNascimento.AllowsNull)
							info.DtNascimento.IsNullValue = true;
					}
					if(dr["ds_cpf"] != System.DBNull.Value)
						info.DsCpf.Value = dr["ds_cpf"].ToString();
					else
					{
						if (info.DsCpf.AllowsNull)
							info.DsCpf.IsNullValue = true;
					}
					if(dr["ds_nome"] != System.DBNull.Value)
						info.DsNome.Value = dr["ds_nome"].ToString();
					else
					{
						if (info.DsNome.AllowsNull)
							info.DsNome.IsNullValue = true;
					}
					if(dr["ds_email"] != System.DBNull.Value)
						info.DsEmail.Value = dr["ds_email"].ToString();
					else
					{
						if (info.DsEmail.AllowsNull)
							info.DsEmail.IsNullValue = true;
					}
					if(dr["ds_endereco"] != System.DBNull.Value)
						info.DsEndereco.Value = dr["ds_endereco"].ToString();
					else
					{
						if (info.DsEndereco.AllowsNull)
							info.DsEndereco.IsNullValue = true;
					}
					lstReturn.Add(info);
				}
			}
			return lstReturn;
		}

		public List<ContatoInfo> ListarPaginado()
		{
			List<ContatoInfo> lstReturn = new List<ContatoInfo>();

			String sqlSelect = "cd_contato, cd_cidade, cd_estado, dt_nascimento, ds_cpf, ds_nome, ds_email, ds_endereco";
			String sqlFrom = "CONTATO";
			String sqlWhere = BuildPagedFilters();
			String sqlOrderBy = BuildPagedOrderBy();
			String sql = new Smart.Database.SQL.Translator(DbHnd.ProviderName).MontarSqlPaginado(sqlSelect, sqlFrom, sqlWhere, sqlOrderBy, this.Filters.PageNumber, this.Filters.EntriesPerPage);
			using (DbDataReader dr = DbHnd.ExecuteReader(sql))
			{
				while (dr.Read())
				{
					ContatoInfo info = new ContatoInfo();
					if(dr["cd_contato"] != System.DBNull.Value)
						info.CdContato.Value = Convert.ToInt32(dr["cd_contato"]);
					else
					{
						if (info.CdContato.AllowsNull)
							info.CdContato.IsNullValue = true;
					}
					if(dr["cd_cidade"] != System.DBNull.Value)
						info.CdCidade.Value = Convert.ToInt32(dr["cd_cidade"]);
					else
					{
						if (info.CdCidade.AllowsNull)
							info.CdCidade.IsNullValue = true;
					}
					if(dr["cd_estado"] != System.DBNull.Value)
						info.CdEstado.Value = Convert.ToInt32(dr["cd_estado"]);
					else
					{
						if (info.CdEstado.AllowsNull)
							info.CdEstado.IsNullValue = true;
					}
					if(dr["dt_nascimento"] != System.DBNull.Value)
						info.DtNascimento.Value = (DateTime)dr["dt_nascimento"];
					else
					{
						if (info.DtNascimento.AllowsNull)
							info.DtNascimento.IsNullValue = true;
					}
					if(dr["ds_cpf"] != System.DBNull.Value)
						info.DsCpf.Value = dr["ds_cpf"].ToString();
					else
					{
						if (info.DsCpf.AllowsNull)
							info.DsCpf.IsNullValue = true;
					}
					if(dr["ds_nome"] != System.DBNull.Value)
						info.DsNome.Value = dr["ds_nome"].ToString();
					else
					{
						if (info.DsNome.AllowsNull)
							info.DsNome.IsNullValue = true;
					}
					if(dr["ds_email"] != System.DBNull.Value)
						info.DsEmail.Value = dr["ds_email"].ToString();
					else
					{
						if (info.DsEmail.AllowsNull)
							info.DsEmail.IsNullValue = true;
					}
					if(dr["ds_endereco"] != System.DBNull.Value)
						info.DsEndereco.Value = dr["ds_endereco"].ToString();
					else
					{
						if (info.DsEndereco.AllowsNull)
							info.DsEndereco.IsNullValue = true;
					}
					lstReturn.Add(info);
				}
			}
			return lstReturn;
		}
		#endregion
	}
}
