using System;
using System.Data.Common;
using Smart.Database;
using Smart.Model;
using System.Collections.Generic;
using GerenciamentoContatos.Model;

namespace GerenciamentoContatos.DAL
{
	public class EstadoDAL : Smart.Model.DataAccessObject
	{
		#region Automaticaly generated by Smart.AutoModeling 2.0
		public EstadoDAL(DbConn pDbHnd) : base (pDbHnd) { }

		public EstadoInfo Get(Int32 pCdEstado)
		{
			DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@cdEstado", pCdEstado));
			String sql = "SELECT cd_estado, ds_estado, ds_uf FROM ESTADO WHERE cd_estado = @cdEstado";
			DbDataReader dr = DbHnd.ExecuteReader(sql);
			try
			{
				if (dr.Read())
				{
					EstadoInfo info = new EstadoInfo();
					if(dr["cd_estado"] != System.DBNull.Value)
						info.CdEstado.Value = Convert.ToInt32(dr["cd_estado"]);
					else
					{
						if (info.CdEstado.AllowsNull)
							info.CdEstado.IsNullValue = true;
					}
					if(dr["ds_estado"] != System.DBNull.Value)
						info.DsEstado.Value = dr["ds_estado"].ToString();
					else
					{
						if (info.DsEstado.AllowsNull)
							info.DsEstado.IsNullValue = true;
					}
					if(dr["ds_uf"] != System.DBNull.Value)
						info.DsUf.Value = dr["ds_uf"].ToString();
					else
					{
						if (info.DsUf.AllowsNull)
							info.DsUf.IsNullValue = true;
					}

					return info;
				}
				else
				{
					return null;
				}
			}
			finally
			{
				dr.Dispose();
			}
		}

		public Int32 Inserir(EstadoInfo pInfo)
		{
			String insertCols = String.Empty;
			String insertValues = String.Empty;
			if (pInfo.DsEstado.ValueIsSet)
			{
				if (!pInfo.DsEstado.IsNullValue)
				{
					DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsEstado", pInfo.DsEstado.Value));
				}
				else
				{
					DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsEstado", System.DBNull.Value));
				}
				insertCols += ", " + pInfo.DsEstado.Name;
				insertValues += ", @dsEstado";
			}
			if (pInfo.DsUf.ValueIsSet)
			{
				if (!pInfo.DsUf.IsNullValue)
				{
					DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsUf", pInfo.DsUf.Value));
				}
				else
				{
					DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsUf", System.DBNull.Value));
				}
				insertCols += ", " + pInfo.DsUf.Name;
				insertValues += ", @dsUf";
			}
			insertCols = insertCols.Substring(2, insertCols.Length - 2);
			insertValues = insertValues.Substring(2, insertValues.Length - 2);
			return DbHnd.InsertGetInt32Key("INSERT INTO ESTADO (" + insertCols + ") VALUES (" + insertValues + ")", "cd_estado");
		}

		public void Atualizar(Int32 pCdEstado, EstadoInfo pInfo)
		{
			String upVars = String.Empty;
			if (pInfo.DsEstado.ValueIsSet)
			{
				if (!pInfo.DsEstado.IsNullValue)
				{
					DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsEstado", pInfo.DsEstado.Value));
				}
				else
				{
					DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsEstado", System.DBNull.Value));
				}
				upVars += ", " + pInfo.DsEstado.Name + " = @dsEstado";
			}
			if (pInfo.DsUf.ValueIsSet)
			{
				if (!pInfo.DsUf.IsNullValue)
				{
					DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsUf", pInfo.DsUf.Value));
				}
				else
				{
					DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsUf", System.DBNull.Value));
				}
				upVars += ", " + pInfo.DsUf.Name + " = @dsUf";
			}
			upVars = upVars.Substring(2, upVars.Length - 2);

			String sqlWhere = String.Empty;
			DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@cdEstado", pCdEstado));
			sqlWhere += "cd_estado = @cdEstado";
			sqlWhere = " WHERE " + sqlWhere;

			DbHnd.ExecuteNonQuery("UPDATE ESTADO SET " + upVars + sqlWhere);
		}

		public void Deletar(Int32 pCdEstado)
		{
			DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@cdEstado", pCdEstado));
			DbHnd.ExecuteNonQuery("DELETE FROM ESTADO WHERE cd_estado = @cdEstado");
		}

		public List<EstadoInfo> Listar()
		{
			List<EstadoInfo> lstReturn = new List<EstadoInfo>();

			String sqlSelect = "cd_estado, ds_estado, ds_uf";
			String sqlFrom = "ESTADO";
			String sqlWhere = BuildFilters();
			String sqlOrderBy = BuildOrderBy();
			String sql = "SELECT " + sqlSelect + " FROM " + sqlFrom + sqlWhere + sqlOrderBy;
			using (DbDataReader dr = DbHnd.ExecuteReader(sql))
			{
				while (dr.Read())
				{
					EstadoInfo info = new EstadoInfo();
					if(dr["cd_estado"] != System.DBNull.Value)
						info.CdEstado.Value = Convert.ToInt32(dr["cd_estado"]);
					else
					{
						if (info.CdEstado.AllowsNull)
							info.CdEstado.IsNullValue = true;
					}
					if(dr["ds_estado"] != System.DBNull.Value)
						info.DsEstado.Value = dr["ds_estado"].ToString();
					else
					{
						if (info.DsEstado.AllowsNull)
							info.DsEstado.IsNullValue = true;
					}
					if(dr["ds_uf"] != System.DBNull.Value)
						info.DsUf.Value = dr["ds_uf"].ToString();
					else
					{
						if (info.DsUf.AllowsNull)
							info.DsUf.IsNullValue = true;
					}
					lstReturn.Add(info);
				}
			}
			return lstReturn;
		}

		public List<EstadoInfo> ListarPaginado()
		{
			List<EstadoInfo> lstReturn = new List<EstadoInfo>();

			String sqlSelect = "cd_estado, ds_estado, ds_uf";
			String sqlFrom = "ESTADO";
			String sqlWhere = BuildPagedFilters();
			String sqlOrderBy = BuildPagedOrderBy();
			String sql = new Smart.Database.SQL.Translator(DbHnd.ProviderName).MontarSqlPaginado(sqlSelect, sqlFrom, sqlWhere, sqlOrderBy, this.Filters.PageNumber, this.Filters.EntriesPerPage);
			using (DbDataReader dr = DbHnd.ExecuteReader(sql))
			{
				while (dr.Read())
				{
					EstadoInfo info = new EstadoInfo();
					if(dr["cd_estado"] != System.DBNull.Value)
						info.CdEstado.Value = Convert.ToInt32(dr["cd_estado"]);
					else
					{
						if (info.CdEstado.AllowsNull)
							info.CdEstado.IsNullValue = true;
					}
					if(dr["ds_estado"] != System.DBNull.Value)
						info.DsEstado.Value = dr["ds_estado"].ToString();
					else
					{
						if (info.DsEstado.AllowsNull)
							info.DsEstado.IsNullValue = true;
					}
					if(dr["ds_uf"] != System.DBNull.Value)
						info.DsUf.Value = dr["ds_uf"].ToString();
					else
					{
						if (info.DsUf.AllowsNull)
							info.DsUf.IsNullValue = true;
					}
					lstReturn.Add(info);
				}
			}
			return lstReturn;
		}
		#endregion
	}
}
